server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  devtools:
    restart:
      enabled: false

logging:
  level:
    root: info
    com.eqnwngg: debug
  file:
    path: log/blog-pro
